spring:
  application:
    name: microservices-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aakarshit/microservices-config-properties.git
          clone-on-start: true
server:
  port: 8888
